### ISSUE TITLE
Webdriver test errors

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1085]
# Issue Description
We started seeing various errors on travis CI related to webdriver. The error messages are some what consistent around errors with before/after hooks.

<details>
 <summary>Sample Error message</summary>
<pre><code>/home/travis/build/cerner/terra-core/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381
            if (!suiteStats.tests[uid]) throw Error(`Unrecognised test [${runner.title}] for suite [${runner.parent}]`);
                                        ^

Error: Unrecognised test ["before all" hook] for suite [Aligned All]
    at ReporterStats.getTestStats (/home/travis/build/cerner/terra-core/node_modules/webdriverio/build/lib/utils/ReporterStats.js:381:47)
    at ReporterStats.testFail (/home/travis/build/cerner/terra-core/node_modules/webdriverio/build/lib/utils/ReporterStats.js:450:30)
    at BaseReporter.<anonymous> (/home/travis/build/cerner/terra-core/node_modules/webdriverio/build/lib/utils/BaseReporter.js:159:25)
    at emitOne (events.js:116:13)
    at BaseReporter.emit (events.js:211:7)
    at BaseReporter.handleEvent (/home/travis/build/cerner/terra-core/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/home/travis/build/cerner/terra-core/node_modules/webdriverio/build/lib/launcher.js:646:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
npm ERR! Test failed.  See above for more details.</code></pre>
</details>

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Tests pass on travis CI

## Current Behavior
Tests seem to fail sporadically with errors related to webdriver.io

**Comment by bjankord** [comment]
Possible related issue https://github.com/webdriverio/webdriverio/issues/2494

**Comment by bjankord** [comment]
It looks like pinning the version of webdriver to 4.9.9 fixed some of the issues, though some PRs are still failing. See the following PRS: 
* https://github.com/cerner/terra-core/pull/1072
* https://github.com/cerner/terra-core/pull/1059
* https://github.com/cerner/terra-core/pull/1054

Not sure if this is a threshold issue on the visual diff that needs bumped to 0.5 we were talking about or another issue.

**Comment by bjankord** [comment]
Another odd thing is the build for [this PR](https://github.com/cerner/terra-core/pull/1086) which pinned the webdriver version passed but once it was merged down to master, the build for master failed.

**Comment by mhemesath** [comment]
I think I have an idea of what may be causing this. Toolkit 2.4 set maxInstances to 3 to utlitize the selenium hub. However, travis still only has 1 instance so this is causing tests to timeout as they pile up waiting for a browser. I'll shoot out a PR to address this.

**Comment by mhemesath** [comment]
Also, a bunch of the PRs are failing because toolkit 2.4 PR removed the custom commands in favor of the `Terra.should.themeEachCustomProperty` command. I left comments on the PRs to update to this.
