### ISSUE TITLE
terra-i18n-plugin should create intermediate directories as required for aggregated-translations

### ISSUE THREAD

**Issue by ajlende** [cerner/terra-core#1247]
# Issue Description

I am trying to put `aggregated-translations` into my build directory which is named `dist`, but it errors with `ENOENT: no such file or directory` instead of creating the `dist` directory.

Obviously, I can add `mkdir dist` to my build script, but it's something that I would expect the plugin to handle.

<details>
<summary>Error details</summary>

```
Error: ENOENT: no such file or directory, mkdir '/Users/me/Documents/my-project/dist/aggregated-translations'
  at Object.fs.mkdirSync (fs.js:885:18)
  at Compiler.<anonymous> (/Users/me/Documents/my-project/node_modules/terra-i18n-plugin/lib/I18nAggregatorPlugin.js:111:26)
  at Compiler.applyPlugins (/Users/me/Documents/my-project/node_modules/tapable/lib/Tapable.js:61:14)
  at webpack (/Users/me/Documents/my-project/node_modules/webpack/lib/webpack.js:36:12)
  at Plugin (/Users/me/Documents/my-project/node_modules/karma-webpack/lib/karma-webpack.js:68:16)
  at invoke (/Users/me/Documents/my-project/node_modules/di/lib/injector.js:75:15)
  at Array.instantiate (/Users/me/Documents/my-project/node_modules/di/lib/injector.js:59:20)
  at get (/Users/me/Documents/my-project/node_modules/di/lib/injector.js:48:43)
  at /Users/me/Documents/my-project/node_modules/di/lib/injector.js:71:14
  at Array.map (<anonymous>)
  at Array.invoke (/Users/me/Documents/my-project/node_modules/di/lib/injector.js:70:31)
  at Injector.get (/Users/me/Documents/my-project/node_modules/di/lib/injector.js:48:43)
  at instantiatePreprocessor (/Users/me/Documents/my-project/node_modules/karma/lib/preprocessor.js:55:20)
  at Array.forEach (<anonymous>)
  at createPreprocessor (/Users/me/Documents/my-project/node_modules/karma/lib/preprocessor.js:74:20)
  at Array.invoke (/Users/me/Documents/my-project/node_modules/di/lib/injector.js:75:15)
```
</details><br>

<details>
<summary>Example <code>webpack.config.js</code></summary>

```js
import …

const src = path.resolve(__dirname, 'src');
const dist = path.resolve(__dirname, 'dist');
const translations = path.resolve(dist, 'aggregated-translations');

module.exports = {
  entry: path.resolve(src, 'app.js'),
  output: {
    path: dist,
    filename: 'bundle.js',
  },
  resolve: {
    extensions: ['.js', '.jsx'],
    modules: [src, translations, 'node_modules'],
  },
  plugins: [
    new I18nAggregatorPlugin({
      baseDirectory: dist,
      translationsDirectories: [src],
      supportedLocales: i18nSupportedLocales,
    }),
  ],
  ⋮
};
```
</details><br>

Additionally, most Webpack plugins, from my experience, default to the output directory which . This just confused me at first when I was getting things set up so I thought I should mention it.

<details>
<summary>Equivalent <code>webpack.config.js</code> for this alternative way of configuring the output directory</summary>

```js
import …

const src = path.resolve(__dirname, 'src');
const dist = path.resolve(__dirname, 'dist');
const translations = path.resolve(dist, 'aggregated-translations'); // This could be anything now, even dist

module.exports = {
  entry: path.resolve(src, 'app.js'),
  output: {
    path: dist,
    filename: 'bundle.js',
  },
  resolve: {
    extensions: ['.js', '.jsx'],
    modules: [src, translations, 'node_modules'],
  },
  plugins: [
    new I18nAggregatorPlugin({
      translationsOutputDirectory: translations, // Only difference is this line
      translationsDirectories: [src],
      supportedLocales: i18nSupportedLocales,
    }),
  ],
  ⋮
};
```
</details>

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

`terra-i18n-plugin` should create intermediate directories as required like `mkdir -p` does when outputting `aggregated-translations` to `baseDirectory` when `baseDirectory` does not exist.

## Current Behavior

Webpack build fails with `ENOENT: no such file or directory`.

**Comment by mjhenkes** [comment]
@ajlende, The reason this plugin doesn't default to the output directory is because the aggregated translations themselves are a pre-compilation step that acts as input into creating your bundle and do not themselves need to be exported or served up as assets.

**Comment by ajlende** [comment]
I guess that makes sense. I'm using them as externals in my webpack config for the backend which is why they made sense to be in dist for me.
