### ISSUE TITLE
Unable to build NPM modules with terra-table

### ISSUE THREAD

**Issue by jdnarvaez** [cerner/terra-core#1447]
# Issue Description
I've added terra-table as a dependency and when trying to build my project it now fails with the following error:

```
npm ERR! path /Users/jn015941/Workspaces/pacs_viewer_engine/client/node_modules/.staging/terra-i18n-d0b4149a
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/jn015941/Workspaces/pacs_viewer_engine/client/node_modules/.staging/terra-i18n-d0b4149a' -> '/Users/jn015941/Workspaces/pacs-viewer-component/node_modules/terra-table/node_modules/terra-i18n'
npm ERR! enoent This is related to npm not being able to find a file.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'rails-server:local' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'prerails-server:local',
4 verbose run-script   'rails-server:local',
4 verbose run-script   'postrails-server:local' ]
5 info lifecycle pacs_viewer_engine@~prerails-server:local: pacs_viewer_engine@
6 info lifecycle pacs_viewer_engine@~rails-server:local: pacs_viewer_engine@
7 verbose lifecycle pacs_viewer_engine@~rails-server:local: unsafe-perm in lifecycle true
8 verbose lifecycle pacs_viewer_engine@~rails-server:local: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/jn015941/Workspaces/pacs_viewer_engine/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/Users/jn015941/.rbenv/shims:/Users/jn015941/.rvm/gems/ruby-2.4.2@pacs_viewer_engine/bin:/Users/jn015941/.rvm/gems/ruby-2.4.2@global/bin:/Users/jn015941/.rvm/rubies/ruby-2.4.2/bin:/Users/jn015941/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jn015941/Workspaces/apache-maven/bin
9 verbose lifecycle pacs_viewer_engine@~rails-server:local: CWD: /Users/jn015941/Workspaces/pacs_viewer_engine
10 silly lifecycle pacs_viewer_engine@~rails-server:local: Args: [ '-c',
10 silly lifecycle   'npm run clean:all:local && cd ../pacs-viewer-component && npm install && cd ../pacs_viewer_engine && npm install && npm run build:development && npm run rails-server' ]
11 silly lifecycle pacs_viewer_engine@~rails-server:local: Returned: code: 254  signal: null
12 info lifecycle pacs_viewer_engine@~rails-server:local: Failed to exec rails-server:local script
13 verbose stack Error: pacs_viewer_engine@ rails-server:local: `npm run clean:all:local && cd ../pacs-viewer-component && npm install && cd ../pacs_viewer_engine && npm install && npm run build:development && npm run rails-server`
13 verbose stack Exit status 254
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid pacs_viewer_engine@
15 verbose cwd /Users/jn015941/Workspaces/pacs_viewer_engine
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.9.0/bin/node" "/usr/local/bin/npm" "run" "rails-server:local"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 254
22 error pacs_viewer_engine@ rails-server:local: `npm run clean:all:local && cd ../pacs-viewer-component && npm install && cd ../pacs_viewer_engine && npm install && npm run build:development && npm run rails-server`
22 error Exit status 254
23 error Failed at the pacs_viewer_engine@ rails-server:local script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 254, true ]
```

This issue seems sporadic but has been happening consistently as of today.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
The project build should not fail because of the dependency.

## Current Behavior
Build fails to complete.

## Steps to Reproduce
Add terra-table and terra-i18n to a project and build it.

## Environment
* Component Version: 2.6.0
* Browser Name and Version: Chrome/Safari
* Operating System and version (desktop or mobile): OS X Sierra

**Comment by emilyrohrbough** [comment]
This log appears to be referencing an issue with your terra-i18n dependency, not terra-table. Have you ran a clean install on the whole project?

**Comment by jdnarvaez** [comment]
I have deleted all node modules directories and it still fails. If you look at the log it appears that the transitive i18n dependency from terra-table is what is failing.

**Comment by emilyrohrbough** [comment]
Do you have the full log output?

**Comment by bjankord** [comment]
Needs more info to be actionable.
