### ISSUE TITLE
Unable to build project with terra-i18n

### ISSUE THREAD

**Issue by jsrsatish** [cerner/terra-core#1505]
# Issue Description
I've added terra-i18n as a dependency and when trying to build my project it fails with the following error:

```
/Users/sk048480/Documents/submissions/devOps/submissions/node_modules/terra-i18n/scripts/aggregate-translations/aggregate-messages.js:21
  );
  ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sk048480/Documents/submissions/devOps/submissions/node_modules/terra-i18n/scripts/aggregate-translations/aggregate-translations.js:6:27)
    at Module._compile (module.js:570:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
The project build should not fail because of the dependency.

## Current Behavior
Build fails to complete.

## Steps to Reproduce
1. Add terra-i18n to a project
2. In webpack.config.js add translation dependencies as per the [aggregate-translations setup steps](https://github.com/cerner/terra-core/blob/master/packages/terra-i18n/docs/AggregateTranslations.md) 
3. Build the project

## Environment

* Component Version: 2.6.0
* Browser Name and Version: Chrome/Safari
* Operating System and version (desktop or mobile): OS X Sierra

**Comment by bjankord** [comment]
The aggregate translations pre-build script has moved to terra-toolkit. The [linked docs](https://github.com/cerner/terra-core/blob/master/packages/terra-i18n/docs/AggregateTranslations.md need to be updated to better note this. Can you try following the docs [noted here](https://github.com/cerner/terra-toolkit/blob/master/docs/AggregateTranslations.md) and see if the issue is resolved.
