### ISSUE TITLE
[axe-core warning] - Ensures aria-hidden elements do not contain focusable elements

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2387]
# Feature Request

When the overlay is open, we set aria-hidden on the root element to prevent VoiceOver on iOS from shifting the virtual cursor outside of the overlay. 

However, we don't currently do anything to disable children within the aria-hidden="true" element.

Adding the inert polyfill we added to abstract modal should hopefully help resolve this.en.

## Description
<details>
 <summary>WDIO Axe Error Report</summary>

```
16) Overlay Overlay on Request-Close OnRequestClose- Full Screen Overlay is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div id=\"root\" aria-hidden=\"true\">",
      "impact": "serious",
      "none": [],
      "target": [
        "#root"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div id=\"root\" aria-hidden=\"true\">",
      "impact": "serious",
      "none": [],
      "target": [
        "#root"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

17) Overlay Overlay on Request-Close Full Screen Overlay- Triggers an onRequestClose on escape keydown is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div id=\"root\" aria-hidden=\"true\">",
      "impact": "serious",
      "none": [],
      "target": [
        "#root"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div id=\"root\" aria-hidden=\"true\">",
      "impact": "serious",
      "none": [],
      "target": [
        "#root"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

18) Overlay Overlay on Request-Close Full Screen Overlay- Triggers an onRequestClose on click inside of the Overlay is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div id=\"root\" aria-hidden=\"true\">",
      "impact": "serious",
      "none": [],
      "target": [
        "#root"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div id=\"root\" aria-hidden=\"true\">",
      "impact": "serious",
      "none": [],
      "target": [
        "#root"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

19) Overlay Overlay on Request-Close OnRequestClose- Container Overlay is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

20) Overlay Overlay on Request-Close Container Overlay- Triggers an onRequestClose on escape keydown is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

21) Overlay Overlay on Request-Close Container Overlay-Triggers an onRequestClose on click inside of the Overlay is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

22) Overlay Custom Content Full Screen Custom Content is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"random_button\">A Random Button To Change Toggle State </button>",
              "target": [
                "#random_button"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div id=\"root\" aria-hidden=\"true\">",
      "impact": "serious",
      "none": [],
      "target": [
        "#root"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"random_button\">A Random Button To Change Toggle State </button>",
              "target": [
                "#random_button"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div id=\"root\" aria-hidden=\"true\">",
      "impact": "serious",
      "none": [],
      "target": [
        "#root"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

23) Overlay Custom Content Container Custom Content is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

24) Overlay Custom Content Custom Content under overlay container is clickable when overlaycontainer is open is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures aria-hidden elements do not contain focusable elements",
  "help": "ARIA hidden element must not contain focusable elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=axeAPI",
  "id": "aria-hidden-focus",
  "impact": "serious",
  "nodes": [
    {
      "all": [
        {
          "data": null,
          "id": "focusable-disabled",
          "impact": "serious",
          "message": "Focusable content should be disabled or be removed from the DOM",
          "relatedNodes": [
            {
              "html": "<button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button>",
              "target": [
                "#trigger_fullscreen"
              ]
            },
            {
              "html": "<button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button>",
              "target": [
                "#trigger_container"
              ]
            }
          ]
        }
      ],
      "any": [],
      "failureSummary": "Fix all of the following:\n  Focusable content should be disabled or be removed from the DOM",
      "html": "<div class=\"Overlay-module__container-content___2Bagf\" tabindex=\"-1\" aria-hidden=\"true\"><button type=\"button\" id=\"trigger_fullscreen\">Trigger Fullscreen Overlay</button><button type=\"button\" id=\"trigger_container\">Trigger Container Overlay</button></div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Overlay-module__container-content___2Bagf"
      ]
    }
  ],
  "tags": [
    "cat.name-role-value",
    "wcag2a",
    "wcag412"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)
```
</details>

**Comment by bjankord** [comment]
Adding the inert polyfill has resolved keyboard focus within the aria-hidden container.
