### ISSUE TITLE
[axe-core warning] - Ensure role attribute has an appropriate value for the element

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2388]
# Feature Request

In terra-list, there is a list element with role="heading" on it. This role should likely be moved to a child element of the list item instead.

## Description
<details>
 <summary>WDIO Axe Error Report</summary>

```
12) List ListSection Test is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures role attribute has an appropriate value for the element",
  "help": "ARIA role must be appropriate for the element",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI",
  "id": "aria-allowed-role",
  "impact": "minor",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"true\" aria-level=\"1\" data-item-show-focus=\"true\" class=\"ListSectionHeader-module__section-header___5CyoH ListSectionHeader-module__is-collapsible___sTHRj\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSectionHeader-module__is-collapsible___sTHRj[role=\"heading\"][aria-level=\"\\31 \"]:nth-child(3)"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"false\" aria-level=\"1\" data-item-show-focus=\"true\" class=\"ListSectionHeader-module__section-header___5CyoH ListSectionHeader-module__is-collapsible___sTHRj\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSectionHeader-module__is-collapsible___sTHRj[role=\"heading\"][aria-level=\"\\31 \"]:nth-child(5)"
      ]
    }
  ],
  "tags": [
    "cat.aria",
    "best-practice"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures role attribute has an appropriate value for the element",
  "help": "ARIA role must be appropriate for the element",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI",
  "id": "aria-allowed-role",
  "impact": "minor",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"true\" aria-level=\"1\" data-item-show-focus=\"true\" class=\"ListSectionHeader-module__section-header___5CyoH ListSectionHeader-module__is-collapsible___sTHRj\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSectionHeader-module__is-collapsible___sTHRj[role=\"heading\"][aria-level=\"\\31 \"]:nth-child(3)"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"false\" aria-level=\"1\" data-item-show-focus=\"true\" class=\"ListSectionHeader-module__section-header___5CyoH ListSectionHeader-module__is-collapsible___sTHRj\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSectionHeader-module__is-collapsible___sTHRj[role=\"heading\"][aria-level=\"\\31 \"]:nth-child(5)"
      ]
    }
  ],
  "tags": [
    "cat.aria",
    "best-practice"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

13) List ListSubsection Test is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures role attribute has an appropriate value for the element",
  "help": "ARIA role must be appropriate for the element",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI",
  "id": "aria-allowed-role",
  "impact": "minor",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"true\" aria-level=\"2\" data-item-show-focus=\"true\" class=\"ListSubsectionHeader-module__subsection-header___1TDDx ListSubsectionHeader-module__is-collapsible___QaYNl\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSubsectionHeader-module__is-collapsible___QaYNl[role=\"heading\"][aria-level=\"\\32 \"]:nth-child(3)"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"false\" aria-level=\"2\" data-item-show-focus=\"true\" class=\"ListSubsectionHeader-module__subsection-header___1TDDx ListSubsectionHeader-module__is-collapsible___QaYNl\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSubsectionHeader-module__is-collapsible___QaYNl[role=\"heading\"][aria-level=\"\\32 \"]:nth-child(5)"
      ]
    }
  ],
  "tags": [
    "cat.aria",
    "best-practice"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures role attribute has an appropriate value for the element",
  "help": "ARIA role must be appropriate for the element",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI",
  "id": "aria-allowed-role",
  "impact": "minor",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"true\" aria-level=\"2\" data-item-show-focus=\"true\" class=\"ListSubsectionHeader-module__subsection-header___1TDDx ListSubsectionHeader-module__is-collapsible___QaYNl\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSubsectionHeader-module__is-collapsible___QaYNl[role=\"heading\"][aria-level=\"\\32 \"]:nth-child(3)"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"false\" aria-level=\"2\" data-item-show-focus=\"true\" class=\"ListSubsectionHeader-module__subsection-header___1TDDx ListSubsectionHeader-module__is-collapsible___QaYNl\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSubsectionHeader-module__is-collapsible___QaYNl[role=\"heading\"][aria-level=\"\\32 \"]:nth-child(5)"
      ]
    }
  ],
  "tags": [
    "cat.aria",
    "best-practice"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

14) List ListSectionHeader Test is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures role attribute has an appropriate value for the element",
  "help": "ARIA role must be appropriate for the element",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI",
  "id": "aria-allowed-role",
  "impact": "minor",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li id=\"test-header\" tabindex=\"0\" role=\"heading\" aria-expanded=\"true\" aria-level=\"1\" data-item-show-focus=\"true\" class=\"ListSectionHeader-module__section-header___5CyoH ListSectionHeader-module__is-collapsible___sTHRj\">",
      "impact": "minor",
      "none": [],
      "target": [
        "#test-header"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"false\" aria-level=\"1\" data-item-show-focus=\"true\" class=\"ListSectionHeader-module__section-header___5CyoH ListSectionHeader-module__is-collapsible___sTHRj\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSectionHeader-module__is-collapsible___sTHRj[role=\"heading\"][aria-level=\"\\31 \"]:nth-child(3)"
      ]
    }
  ],
  "tags": [
    "cat.aria",
    "best-practice"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures role attribute has an appropriate value for the element",
  "help": "ARIA role must be appropriate for the element",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI",
  "id": "aria-allowed-role",
  "impact": "minor",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li id=\"test-header\" tabindex=\"0\" role=\"heading\" aria-expanded=\"true\" aria-level=\"1\" data-item-show-focus=\"true\" class=\"ListSectionHeader-module__section-header___5CyoH ListSectionHeader-module__is-collapsible___sTHRj\">",
      "impact": "minor",
      "none": [],
      "target": [
        "#test-header"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"false\" aria-level=\"1\" data-item-show-focus=\"true\" class=\"ListSectionHeader-module__section-header___5CyoH ListSectionHeader-module__is-collapsible___sTHRj\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSectionHeader-module__is-collapsible___sTHRj[role=\"heading\"][aria-level=\"\\31 \"]:nth-child(3)"
      ]
    }
  ],
  "tags": [
    "cat.aria",
    "best-practice"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

15) List ListSubsectionHeader Test is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures role attribute has an appropriate value for the element",
  "help": "ARIA role must be appropriate for the element",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI",
  "id": "aria-allowed-role",
  "impact": "minor",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li id=\"test-header\" tabindex=\"0\" role=\"heading\" aria-expanded=\"true\" aria-level=\"2\" data-item-show-focus=\"true\" class=\"ListSubsectionHeader-module__subsection-header___1TDDx ListSubsectionHeader-module__is-collapsible___QaYNl\">",
      "impact": "minor",
      "none": [],
      "target": [
        "#test-header"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"false\" aria-level=\"2\" data-item-show-focus=\"true\" class=\"ListSubsectionHeader-module__subsection-header___1TDDx ListSubsectionHeader-module__is-collapsible___QaYNl\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSubsectionHeader-module__is-collapsible___QaYNl[role=\"heading\"][aria-level=\"\\32 \"]:nth-child(3)"
      ]
    }
  ],
  "tags": [
    "cat.aria",
    "best-practice"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures role attribute has an appropriate value for the element",
  "help": "ARIA role must be appropriate for the element",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI",
  "id": "aria-allowed-role",
  "impact": "minor",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li id=\"test-header\" tabindex=\"0\" role=\"heading\" aria-expanded=\"true\" aria-level=\"2\" data-item-show-focus=\"true\" class=\"ListSubsectionHeader-module__subsection-header___1TDDx ListSubsectionHeader-module__is-collapsible___QaYNl\">",
      "impact": "minor",
      "none": [],
      "target": [
        "#test-header"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": [
            "heading"
          ],
          "id": "aria-allowed-role",
          "impact": "minor",
          "message": "ARIA role heading  is not allowed for given element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  ARIA role heading  is not allowed for given element",
      "html": "<li tabindex=\"0\" role=\"heading\" aria-expanded=\"false\" aria-level=\"2\" data-item-show-focus=\"true\" class=\"ListSubsectionHeader-module__subsection-header___1TDDx ListSubsectionHeader-module__is-collapsible___QaYNl\">",
      "impact": "minor",
      "none": [],
      "target": [
        ".ListSubsectionHeader-module__is-collapsible___QaYNl[role=\"heading\"][aria-level=\"\\32 \"]:nth-child(3)"
      ]
    }
  ],
  "tags": [
    "cat.aria",
    "best-practice"
  ]
}
```
</details>

**Comment by emilyrohrbough** [comment]
@bjankord I think this is a non-issue. If you look at the tags specified in the output, each validation lists the tags `cat.aria` and `best-practice` as the effected rules. Terra only supports WCAG 2.0 and Section 508, which axe-core will reference these as `wcag2a `, `wcag2aa` and `section508`. Do you know if we are supporting WCAG 2.0 A or AA?

**Comment by CamWandfluh** [comment]
@emilyrohrbough I believe we are supposed to be WCAG 2.0 A and AA compliant. https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/text-of-the-standards-and-guidelines#E207-software If you look at section 207.2 in the section 508 standards it says all user interface components must conform to WCAG 2.0 A and AA requirements.

**Comment by bjankord** [comment]
We should strive to support WCAG 2.1 AA Guidelines as well as Section 508 compliance.
