### ISSUE TITLE
[axe-core warning] - Ensure that lists are structured correctly

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2390]
# Feature Request

There are 2 places we need to update lists:
* Ensures <li> elements are used semantically
* Need to update terra select optgroup markup to  ensure that lists are structured correctly.

## Description
<details>
 <summary>WDIO Axe Error Report</summary>

   ```
1) List ListItem Test is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures <li> elements are used semantically",
  "help": "<li> elements must be contained in a <ul> or <ol>",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/listitem?application=axeAPI",
  "id": "listitem",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": null,
          "id": "listitem",
          "impact": "serious",
          "message": "List item does not have a <ul>, <ol> or role=\"list\" parent element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  List item does not have a <ul>, <ol> or role=\"list\" parent element",
      "html": "<li class=\"List-module__list-item___KZgJ6\"><div class=\"List-module__item-fill___2aQEW\"><p>test default</p></div></li>",
      "impact": "serious",
      "none": [],
      "target": [
        "li:nth-child(1)"
      ]
    },
    {
      "all": [],
      "any": [
        {
          "data": null,
          "id": "listitem",
          "impact": "serious",
          "message": "List item does not have a <ul>, <ol> or role=\"list\" parent element",
          "relatedNodes": []
        }
      ],
      "failureSummary": "Fix any of the following:\n  List item does not have a <ul>, <ol> or role=\"list\" parent element",
      "html": "<li class=\"List-module__list-item___KZgJ6\">",
      "impact": "serious",
      "none": [],
      "target": [
        "li:nth-child(2)"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
```

  </summary>
</details>

<details>
 <summary>WDIO Axe Error Report</summary>

```
1) Select Field should select the maximum number of items allowed. is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

2) Select Field should select the maximum number of items allowed. is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

3) Select Field should select the maximum number of items allowed. is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

4) Select Field should select the maximum number of items allowed. is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

5) Select Field should select the maximum number of items allowed. is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

6) Select Field should select the maximum number of items allowed. is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(1) > ._OptGroup-module__options___1NzpX"
      ]
    },
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__opt-group___q_oDc:nth-child(2) > ._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)

7) Select OptGroup should render an optgroup is accessible:
expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
running chrome
AssertionError: expected no accessibility violations but got:
        {
  "description": "Ensures that lists are structured correctly",
  "help": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.2/list?application=axeAPI",
  "id": "list",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [],
      "failureSummary": "Fix all of the following:\n  List element has direct children that are not allowed inside <li> elements",
      "html": "<ul class=\"_OptGroup-module__options___1NzpX\">",
      "impact": "serious",
      "none": [
        {
          "data": null,
          "id": "only-listitems",
          "impact": "serious",
          "message": "List element has direct children that are not allowed inside <li> elements",
          "relatedNodes": []
        }
      ],
      "target": [
        "._OptGroup-module__options___1NzpX"
      ]
    }
  ],
  "tags": [
    "cat.structure",
    "wcag2a",
    "wcag131"
  ]
}
    at Context.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/terra-toolkit/lib/wdio/services/TerraCommands/accessiblity.js:13:54)
    at new Promise (<anonymous>)
    at new F (/Users/bj031910/repos/terra-core/node_modules/core-js/library/modules/_export.js:36:28)
```
</details>

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/terra-core/pull/2456
