### ISSUE TITLE
Webpack2 causes Depreciation Warning of loaderUtils.parseQuer()

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#288]
### Description of Issue
The following warning is received when running nightwatch tests with webpack v2.

> (node:9247) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

Discussion regarding the issues is found [here](https://github.com/webpack/loader-utils/issues/56).

**Comment by Matt-Butler** [comment]
```
➜  terra-site git:(master) node --trace-deprecation node_modules/.bin/webpack
(node:13828) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/loader-utils/index.js:78:3)
    at getLoaderConfig (/Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/sass-loader/index.js:387:23)
    at Object.module.exports (/Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/sass-loader/index.js:42:23)
    at LOADER_EXECUTION (/Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /Users/mb034780/public_github/terra-core/packages/terra-site/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

**Comment by Matt-Butler** [comment]
Updating the sass-loader to 6.x removes the deprecation warning.

**Comment by windse7en** [comment]
Update `sass-loader` to 6.0.3 and also upgrade other devDependencies versions.
```
// only in terra-site
devDependencies
    "autoprefixer": "^6.7.7”,
    "babel-loader": "^6.4.1",
    "clean-webpack-plugin": "^0.1.16",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "gh-pages": "^0.12.0”,
    "json-loader": "^0.5.4",
    "node-sass": "^4.5.2",
    "postcss-loader": "^1.3.3",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "style-loader": "^0.13.2",

// also used in terra-toolkit
    "html-webpack-plugin": "^2.28.0”,
    "webpack": "^2.4.1",
    "webpack-dev-server": "^2.4.2"

// also used in terra-core
    "babel-cli": "^6.24.1”,
```
